# https://zenn.dev/yumemi_inc/articles/b3e11b50869c1a

name: auto-assign-assignees

on:
  pull_request:
    types: [opened, ready_for_review]

permissions:
  pull-requests: write
  repository-projects: read

jobs:
  assign:
    name: Assign yourself
    runs-on: ubuntu-latest
    steps:
      - name: Set GitHub assignees
        env: GH_TOKEN: ${{ github.token }}
        run: gh pr edit ${{ github.event.number }} --add-assignee ${{ github.actor }} --repo ${{ github.repository }}
